.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH srvm 1  "srvm 0.1.0"
.SH NAME
srvm \- Zero\-config universal app launcher
.SH SYNOPSIS
\fBsrvm\fR [\fB\-\-dry\-run\fR] [\fB\-\-no\-open\fR] [\fB\-\-port\fR] [\fB\-\-select\fR] [\fB\-\-no\-install\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-\-quiet\fR] [\fB\-\-no\-color\fR] [\fB\-\-all\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIDIR\fR]
.SH DESCRIPTION
Zero\-config universal app launcher
.SH OPTIONS
.TP
\fB\-\-dry\-run\fR

.TP
\fB\-\-no\-open\fR

.TP
\fB\-\-port\fR \fI<PORT>\fR
Start port search at N (0 chooses a free port)
.TP
\fB\-\-select\fR \fI<SELECT>\fR
Run one app: index, qualified id, or a unique name
.TP
\fB\-\-no\-install\fR

.TP
\fB\-v\fR, \fB\-\-verbose\fR

.TP
\fB\-\-quiet\fR

.TP
\fB\-\-no\-color\fR

.TP
\fB\-\-all\fR
Alias for the default set
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIDIR\fR] [default: .]

.SH VERSION
v0.1.0
